### ISSUE TITLE
[1.10.2] Cannot place gates from Integration and pipes from transportation

### ISSUE THREAD

**Issue by Xiaminou** [MrTJP/ProjectRed#1091]
And Framed Low Load Power Line.

https://youtu.be/7qJsnLrBwqA

Environment: Singleplayer
Minecraft: 1.10.2
Forge: 2185
MrTJP: 2.0.0.1
ProjectRed: 4.8.0.1
Mods: [list.txt](https://github.com/MrTJP/ProjectRed/files/742656/list.txt)

**Comment by MrTJP** [comment]
What?? I'm not getting any such bug.. Looking into it some more...

**Comment by MrTJP** [comment]
Any ideas @covers1624? This isn't happening in dev space, didn't test release builds yet...

**Comment by covers1624** [comment]
Not sure, Ill poke morph and see if he can reproduce.

**Comment by Morpheus1101** [comment]
hmm, let me take a look and see what results i get

**Comment by qazzz789** [comment]
Crash Log: [crash-2017-02-03_22.26.35-server.txt](https://github.com/MrTJP/ProjectRed/files/751990/crash-2017-02-03_22.26.35-server.txt)

Environment: single player
Minecraft: 1.10.2
Forge: 1.10.2-12.18.3.2185
Mods: [list.txt](https://github.com/MrTJP/ProjectRed/files/751991/list.txt)

**Comment by RiC0MD** [comment]
I too am seeing this issue, can seem to place everything except transportation pipes and redstone gates (machine blocks seem fine, illumination, etc)

**Comment by MrTJP** [comment]
Issue was in FMP. A fix has been pushed and a new version will be available for download from Curse shortly...

**Comment by Xiaminou** [comment]
Yep, can confirm this is fixed. Congratulations on the 1.10.2 release.

**Comment by RiC0MD** [comment]
Just pulled down the latest files from the wiki and still seeing the issue, am I missing something or has the files not reached curse yet?

**Comment by Xiaminou** [comment]
It is definitely on Curseforge. You must be missing something.

**Comment by RiC0MD** [comment]
@Xiaminou can you link or pm me the FMP, starting to wonder if I'm downloading the wrong one, tia!

**Comment by Xiaminou** [comment]
https://minecraft.curseforge.com/projects/forge-multipart-cbe/files/2377623

**Comment by RiC0MD** [comment]
Thanks!!
