### ISSUE TITLE
[1.10.2] Crash when opening Project Red Backpack

### ISSUE THREAD

**Issue by AaronPLights** [MrTJP/ProjectRed#1194]
Whenever I attempt to open a Project Red backpack, my client freezes and then crashes. 
Not sure if it's due to a specific item inside it or not, client crashes happens when on a local world and on servers.

Crash Log: https://paste.ee/p/OD5ab

Any help would be useful! Thanks

**Comment by NillerUdenDild** [comment]
To add to this: I am unable to open PR backpacks, with any item inside it. I thought the issues might be connected.

Enigmatica modpack, version 3.09a
Minecraft 1.10.2
Forge 12-18.3.2316
ProjectRed 1.10.2-4.8.4.49

**Comment by MrTJP** [comment]
Again, update MrTJPCore. Do not report bugs if you have not tried the latest version of all relevant mods first.

For the second issue, fixed with 5417878c3f7aa26ae9093056cb585f3d988c6d29

**Comment by AaronPLights** [comment]
Yea, the issue is, when the server updated to latest mods players we’re still crashing so the server reverted to a previous version.

Here’s the crash log for latest mods: https://paste.ee/p/xlr9F
Using:
MrTJPCore-1.10.2-2.0.1.20
ProjectRed-1.10.2-4.8.4.49 (Base, Integration, Fabrication, Lightning, World)

The server before was using 4.8.2.41 of the Proj Red Mods with 2.0.0.17 of TJPCore which were latest at the time. It worked then and didn’t crash players on open.
When the server updated to 4.8.3.47 of Proj Red Mods with 2.0.0.19 of TJPCore which was latest before your update from 3-4 days ago the crash started happening with Backpacks. This is where they reverted back to previous versions to prevent any other issues but I guess forgot to revert the core mod.
Now even with the latest of all mods (With the crash log provided there) the crash still happens.

It was a mistake on my side for not specifying that, sorry for that on my end. My guess it's the issue related to NillerUdenDild where items in the backpack but I'm not sure. Just sending this as a update in the case that they are different issues.

**Comment by MrTJP** [comment]
Your players did not update MrTJPCore then (if they are getting the first issue). For some reason Curse did not make it a mandatory update even though the two versions of MrTJPCore were incompatible. Maybe I set something wrong, but updating should fix the issue
